/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/models/megaman_base.glb -T -j
Files: public/models/megaman_base.glb [6.07MB] > /Users/shynn/Projets/_dev/vite-megaman/megaman_base-transformed.glb [1.27MB] (79%)
*/

import { ReactElement, useCallback, useEffect, useRef } from 'react';
import { useAnimations, useGLTF } from '@react-three/drei';
import { invalidate } from '@react-three/fiber';
import useArmorStore from '@stores/useArmorStore';
import useColorSchemeStore from '@stores/useColorSchemeStore';
import { Group } from 'three';

import { MODEL_ARMATURE } from '@constants/constantsModels';
import { useAnimation } from '@contexts/AnimationContext';
import { ActionName } from '@interfaces/animation';
import { GLTFResult } from '@interfaces/gltfResult';
import { preloadModels } from '@utils/preloadModels';

import Chest from './Armature/Chest';
import Eyes from './Armature/Eyes';
import Face from './Armature/Face';
import FootL from './Armature/FootL';
import FootR from './Armature/FootR';
import Forearm_WeaponR from './Armature/Forearm_WeaponR';
import ForearmL from './Armature/ForearmL';
import ForearmR from './Armature/ForearmR';
import Hair from './Armature/Hair';
import HandL from './Armature/HandL';
import HandR from './Armature/HandR';
import Helmet from './Armature/Helmet';
import LowerLegL from './Armature/LowerLegL';
import LowerLegR from './Armature/LowerLegR';
import ShoulderL from './Armature/ShoulderL';
import ShoulderR from './Armature/ShoulderR';
import UpperArmL from './Armature/UpperArmL';
import UpperArmR from './Armature/UpperArmR';
import UpperLegL from './Armature/UpperLegL';
import UpperLegR from './Armature/UpperLegR';
import Waist from './Armature/Waist';

export function MegamanBase(): ReactElement {
  const group = useRef<Group>(null);

  const { nodes, animations } = useGLTF(MODEL_ARMATURE.path) as GLTFResult;

  const { actions } = useAnimations(animations, group);
  const {
    colorStates: { armatureColor },
  } = useColorSchemeStore();
  const { armorVisibility } = useArmorStore();
  const { animationName } = useAnimation();

  // Memoize playAnimation
  const playAnimation = useCallback(
    (type: ActionName) => {
      if (actions[type]) {
        actions[type].reset().play();
        actions[type].clampWhenFinished = true;
        invalidate();
      }
    },
    [actions]
  );

  useEffect(() => {
    if (animationName) {
      playAnimation(animationName as ActionName);
      invalidate(); // Ask for a new frame when the animation changes
    }
  }, [animationName, playAnimation]);

  useEffect(() => {
    return () => {
      if (animationName && animationName in actions) {
        const action = actions[animationName as ActionName];
        if (action) {
          action.stop(); // Stop the current animation
          action.reset(); // Reset the animation
        }
      }
    };
  }, [animationName, actions]);

  useEffect(() => {
    preloadModels();
  }, []);

  return (
    <group ref={group} dispose={null}>
      <group name="Scene">
        <group name="base_armature">
          <group name="bones" rotation={[Math.PI / 2, 0, 0]}>
            <group
              name="waist"
              position={[0, 0, -2.079]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <group
                name="upper_legL"
                position={[0.199, 0.099, -0.002]}
                rotation={[-3.141, 0.003, -0.188]}
              >
                <group
                  name="lower_legL"
                  position={[0, 1.001, 0]}
                  rotation={[0.032, -0.01, 0]}
                >
                  <FootL />
                  <mesh
                    name="armature_lower_legL"
                    geometry={nodes.armature_lower_legL.geometry}
                    material={armatureColor.material}
                    position={[0, 0.786, 0]}
                    rotation={[0.136, -1.561, -1.403]}
                  />
                  <LowerLegL />
                </group>

                <mesh
                  name="armature_kneeL"
                  geometry={nodes.armature_kneeL.geometry}
                  material={armatureColor.material}
                  position={[0, 1.001, 0]}
                  rotation={[-3.067, 1.564, 1.496]}
                />

                <mesh
                  name="armature_upper_legL"
                  geometry={nodes.armature_upper_legL.geometry}
                  material={armatureColor.material}
                  position={[0.001, 0, 0]}
                  rotation={[3.141, -0.982, 1.565]}
                />
                <UpperLegL />
              </group>

              <group
                name="upper_legR"
                position={[-0.199, 0.099, -0.002]}
                rotation={[-3.141, -0.003, 0.188]}
              >
                <group
                  name="lower_legR"
                  position={[0, 1.001, 0]}
                  rotation={[0.032, 0.01, 0]}
                >
                  <FootR />
                  <mesh
                    name="armature_lower_legR"
                    geometry={nodes.armature_lower_legR.geometry}
                    material={armatureColor.material}
                    position={[0, 0.786, 0]}
                    rotation={[-3.006, -1.561, -1.403]}
                    scale={-1}
                  />
                  <LowerLegR />
                </group>

                <mesh
                  name="armature_kneeR"
                  geometry={nodes.armature_kneeR.geometry}
                  material={armatureColor.material}
                  position={[0, 1.001, 0]}
                  rotation={[0.075, 1.564, 1.496]}
                  scale={-1}
                />

                <mesh
                  name="armature_upper_legR"
                  geometry={nodes.armature_upper_legR.geometry}
                  material={armatureColor.material}
                  position={[-0.001, 0, 0]}
                  rotation={[-0.001, -0.982, 1.565]}
                  scale={-1}
                />
                <UpperLegR />
              </group>

              <group name="chest" position={[0, 0.538, 0]}>
                <group name="neck" position={[0, 0.57, 0]}>
                  <group name="head" position={[0, 0.146, 0]}>
                    <Eyes />
                    <Helmet />
                    <Hair />
                    <Face />
                  </group>

                  <mesh
                    name="neck_1"
                    geometry={nodes.neck_1.geometry}
                    material={armatureColor.material}
                    position={[0, -3.187, 0]}
                  />
                </group>

                <group
                  name="upper_armL"
                  position={[0.349, 0.423, 0]}
                  rotation={[0, 0.019, -Math.PI / 2]}
                >
                  <group
                    name="forearmL"
                    position={[0, 0.393, 0]}
                    rotation={[0.032, 0, 0]}
                  >
                    <HandL />
                    <mesh
                      name="armature_forearmL"
                      geometry={nodes.armature_forearmL.geometry}
                      material={armatureColor.material}
                      position={[3.041, -0.742, 0.017]}
                      rotation={[-0.013, 0, Math.PI / 2]}
                    >
                      <mesh
                        name="armature_forearm_ringL"
                        geometry={nodes.armature_forearm_ringL.geometry}
                        material={armatureColor.material}
                      />
                    </mesh>
                    <ForearmL />
                  </group>

                  <mesh
                    name="armature_upper_armL"
                    geometry={nodes.armature_upper_armL.geometry}
                    material={armatureColor.material}
                    position={[0, 0.024, 0]}
                    rotation={[0.019, 0, Math.PI / 2]}
                  />

                  <UpperArmL />
                </group>

                <group
                  name="upper_armR"
                  position={[-0.349, 0.423, 0]}
                  rotation={[0, -0.019, Math.PI / 2]}
                >
                  <group
                    name="forearmR"
                    position={[0, 0.393, 0]}
                    rotation={[0.032, 0, 0]}
                  >
                    {!armorVisibility.weaponR ? <HandR /> : null}
                    <mesh
                      name="armature_forearmR"
                      geometry={nodes.armature_forearmR.geometry}
                      material={armatureColor.material}
                      position={[-3.041, -0.742, 0.017]}
                      rotation={[-0.013, 0, -Math.PI / 2]}
                    >
                      <mesh
                        name="armature_forearm_ringR"
                        geometry={nodes.armature_forearm_ringR.geometry}
                        material={armatureColor.material}
                      />
                    </mesh>
                    {armorVisibility.weaponR ? (
                      <Forearm_WeaponR />
                    ) : (
                      <ForearmR />
                    )}
                  </group>

                  <mesh
                    name="armature_upper_armR"
                    geometry={nodes.armature_upper_armR.geometry}
                    material={armatureColor.material}
                    position={[0, -0.722, -0.014]}
                    rotation={[0.019, 0, -Math.PI / 2]}
                  />
                  <UpperArmR />
                </group>

                <ShoulderL />
                <ShoulderR />
                <mesh
                  name="armature_chest"
                  geometry={nodes.armature_chest.geometry}
                  material={armatureColor.material}
                  position={[0, -2.617, 0]}
                >
                  <mesh
                    name="armature_chest_arms"
                    geometry={nodes.armature_chest_arms.geometry}
                    material={armatureColor.material}
                  />
                </mesh>
                <Chest />
              </group>
              <mesh
                name="armature_waist"
                geometry={nodes.armature_waist.geometry}
                material={armatureColor.material}
                position={[0, 0.538, -0.013]}
              />
              <Waist />
            </group>
            {/* <ArmatureTargets /> */}
          </group>
        </group>
      </group>
    </group>
  );
}
